.pc
.TH Highlighters.rakumod 1 2023-12-06
.SS Table of Contents
.IP \(bu 2m
Introduction [#introduction]
.IP \(bu 2m
HighlighterFailed [#highlighterfailed]
.IP \(bu 2m
highlight\-var [#highlight-var]
.IP \(bu 2m
highlight\-val [#highlight-val]
.SH "NAME"
Syntax::Highlighters 
.SH "AUTHOR"
Francis Grizzly Smit (grizzly@smit\&.id\&.au)
.SH "VERSION"
0\&.1\&.0
.SH "TITLE"
Gzz::Text::Utils
.SH "SUBTITLE"
A Raku module to one basic syntax highlighting\&.
.SH "COPYRIGHT"
LGPL V3\&.0+ LICENSE [https://github.com/grizzlysmit/Syntax-Highlighters/blob/main/LICENSE]
.SH Introduction

Some syntax highlighting stuff: grammars to parse basic \fBRaku\fR forms and highlight them with colours\&. And functions to use them\&.
.SH HighlighterFailed

An Exception class for reporting errors in parsing\&.

.RS 4m
.EX
class HighlighterFailed is Exception is export {
    has Str:D $\&.msg = 'Error: Highlighter Failed\&.';
    method message( \-\-> Str:D) {
        $!msg;
    }
}


.EE
.RE
