.pc
.TH Highlighters.rakumod 1 2023-12-06
.SS Table of Contents
.RS 2n
.IP \(bu 2m
highlight\-var [#highlight-var]
.RE
.RS 2n
.IP \(bu 2m
highlight\-val [#highlight-val]
.RE
.SH "NAME"
Syntax::Highlighters 
.SH "AUTHOR"
Francis Grizzly Smit (grizzly@smit\&.id\&.au)
.SH "VERSION"
0\&.1\&.0
.SH "TITLE"
Gzz::Text::Utils
.SH "SUBTITLE"
A Raku module to provide text formatting services to Raku programs\&.
.SH "COPYRIGHT"
LGPL V3\&.0+ LICENSE [https://github.com/grizzlysmit/Gzz-Text-Utils/blob/main/LICENSE]
.SH some syntax highlighting stuff 
